# Generated by Django 3.0.3 on 2020-06-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoutorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip_address', models.GenericIPAddressField(unique=True)),
                ('Loopback', models.GenericIPAddressField()),
                ('Hostname', models.CharField(max_length=30)),
                ('sap_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=30)),
            ],
        ),
    ]
